lane :beta do
  match(type: 'appstore', team_id: 'A38T799N53', username: 'huacnlee@gmail.com', readonly: true)
  increment_build_number
  gym(scheme: "Ruby China",
      workspace: "ruby-china-ios.xcworkspace")
  changelog_from_git_commits
  testflight
end

lane :appstore do
  match(type: 'appstore')
  snapshot
  pem
  gym(scheme: "Ruby China")
  appstore
end