lane :beta do
  match(type: 'appstore')
  increment_build_number
  gym(scheme: "Ruby China",
      silent: true,
      clean: false,
      workspace: "ruby-china-ios.xcworkspace")
  changelog_from_git_commits
  testflight(username: 'huacnlee@gmail.com', skip_waiting_for_build_processing: true)
end

lane :appstore do
  match(type: 'appstore')
  snapshot
  pem
  gym(scheme: "Ruby China")
  appstore
end