lane :beta do
  match(type: 'appstore')
  increment_build_number
  gym(scheme: "Ruby China",
      workspace: "ruby-china-ios.xcworkspace")
  changelog_from_git_commits
  testflight(username: 'huacnlee@gmail.com', itc_team_id: '118076100')
end

lane :appstore do
  match(type: 'appstore')
  snapshot
  pem
  gym(scheme: "Ruby China")
  appstore
end